spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: mysql1 #设置默认数据库源
      strict: false #严格匹配数据源，默认为false，true未匹配到指定数据库时抛异常，false使用默认数据源
      datasource:
        mysql1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/demo_mybatisplus?serverTimezone=UTC
          username: root
          password: root
#          type: com.alibaba.druid.pool.DruidDataSource
        mysql2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/demo_mybatisplus2?serverTimezone=UTC
          username: root
          password: root
#          type: com.alibaba.druid.pool.DruidDataSource

